### ISSUE TITLE
US Squad Leaders get the "# Squad" before and after the @

### ISSUE THREAD

**Issue by Drofseh** [FakeMessiah27/2.PzDLoadoutFileEditor#5]
For example:
`1 Squad | Squad Leader@1 Platoon | 1 Squad`

Should be:
` Squad Leader@1 Platoon | 1 Squad`

**Comment by FakeMessiah27** [comment]
Could not reproduce error. All files look fine on my end. Will re-build and re-upload the release version of the .jar just in case something went wrong there.
